# Generated by Django 4.0.4 on 2022-05-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ninjaname',
            options={'ordering': ['type']},
        ),
        migrations.AddField(
            model_name='ninjaname',
            name='type',
            field=models.CharField(choices=[('ADJ', 'Adjective'), ('NOUN', 'Noun')], default='ADJ', max_length=4),
        ),
    ]
